import "./globals.css";
import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";

import Footer from "./components/Footer";

const lexend = Nunito_Sans({
  weight: ["500", "600", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hliki Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lexend.className}>{children}</body>
      <Footer />
    </html>
  );
}
