import "./globals.css";
import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "./components/Footer";
import { Suspense } from "react";

const lexend = Nunito_Sans({
  weight: ["500", "600", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hliki Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={lexend.className}>
          {children}
          <Suspense fallback={<p>Loading feed...</p>}>
            <Footer />
          </Suspense>
        </body>
      </html>
    </ClerkProvider>
  );
}
